name: NCTL Scan Pipeline Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  NIRMATA_TOKEN: ${{ secrets.NIRMATA_TOKEN }}
  NIRMATA_URL: ${{ secrets.NIRMATA_URL }}


jobs:
  NCTL-Scan-Repository:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          # Checks out the repository linked to the PR
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # Checks out the branch from the PR
          ref: ${{ github.event.pull_request.head.ref }}

      # - name: Install nctl
      #   uses: nirmata/action-install-nctl-scan@v0.0.9

      - name: nctl-scan-installer
        uses: supplypike/setup-bin@v4
        with:
          uri: https://dl.nirmata.io/nctl/nctl_4.2.3/nctl_4.2.3_linux_386.zip
          name: 'nctl'
          version: '4.2.3'

      - name: Check nctl version
        run: |
          nctl version

      - name: nctl login
        run: nctl login --url $NIRMATA_URL --userid anusha.hegde@nirmata.com --token $NIRMATA_TOKEN

      - name: NCTL Scan Repository
        run: |
          nctl scan repository --policy-sets pss-baseline,pss-restricted,dockerfile-best-practices  --publish-token $NIRMATA_TOKEN --details
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
